# Whether the plugin will send action bar announcements
enabled: true
# Go through the announcement list in a random order
random-order: false
# Time (in seconds) between announcements
interval: 20
# List of announcements
announcements:
  # Announcements for unspecified worlds
  global:
    - Welcome to the server
    - Have a great time %player%
    - There are currently %online% players online!
  world_nether:
    - The Nether is a fun place
    - Do /help for help!
# Send an announcement when the player joins the server
send-on-join: false
# If the above is enabled this message will be sent to players when they join
join-announcement: "Welcome to the server %player% :)"

# %command-usage% - The command being used incorrectly
messages:
  no-permissions: "&cYou have insufficient permissions."
  incorrect-usage: "&7Incorrect Usage, try &c%command-usage%"
  reloaded: "&aActionBarAnnouncements has been reloaded."
  muted: "&7ActionBarAnnouncements have been muted"
  unmuted: "&7ActionBarAnnouncements have been unmuted"